safe:           true
lsi:            false
pygments:       true
timezone:       America/Los_Angeles
markdown:       kramdown

paginate:       10
paginate_path:  "news/page:num"

name:           Seattle GNU Linux Conference
description:    Seattle GNU Linux Conference
url:            http://seagl.org
